export const LOAD_GAMES = "LOAD_GAMES";
export const GET_GAME = "GET_GAME";
export const DELETE_GAME = "DELETE_GAME";
export const ADD_GAME = "ADD_GAME";

export const LOAD_GAME_TYPES = "LOAD_GAME_TYPES";
export const GET_GAME_TYPE = "GET_GAME_TYPE";

export const LOAD_PLACES = "LOAD_PLACES";
export const GET_PLACE = "GET_PLACE";

export const LOAD_PLAYER_INVITATIONS = "LOAD_PLAYER_INVITATIONS";

export const ADD_PLAYER_INVITATION = "ADD_PLAYER_INVITATION";
export const DELETE_PLAYER_INVITATION = "DELETE_PLAYER_INVITATION";
